items_edit
shunsyun/freemarket_sample_52c pull request #68
Opened 2019-06-30 09:11 UTC by RyoheiKoga

# what
出品編集画面実装

# why
添削のため

2019-06-30 09:21 UTC, RyoheiKoga commented
https://gyazo.com/072f7f524a0baa775e3676986e360509
https://gyazo.com/c55a52d85276d3652b1090f18b8a7d15

2019-06-30 09:28 UTC, yuki-uchida requested changes

2019-06-30 09:28 UTC, yuki-uchida commented on app/views/items/_form.html.haml
> +                          %option{value: 0} ---
この辺りはactivehashで管理しましょう。
この項目が増えた時に地獄を見ることになります

2019-07-02 03:17 UTC, RyoheiKoga commented
# what
edit画面のactivehashで追記
ルーティングの修正

# why
可視性、シンプルなコード化

# メンターさん
いつもお疲れ様です。
よろしくお願いします。

2019-07-02 03:18 UTC, RyoheiKoga commented
# 画像
https://i.gyazo.com/6238ce084d5551fd0285034a501f351c.gif
https://i.gyazo.com/cb1d3a8e130bc35a25695b05067a7832.gif

2019-07-02 03:22 UTC, shingoteshima commented on app/controllers/items_controller.rb
> +    @item = Item.find(params[:id])
@item = Item.find(params[:id])こちらset_itemのようにメソッドにし、before_actionで呼び出しましょう。

2019-07-02 03:22 UTC, shingoteshima commented on app/models/Prefecture2.rb
> +class Prefecture2 < ActiveHash::Base
Prefecture2という名前は適切ではないですね。

2019-07-02 03:22 UTC, shingoteshima commented on app/models/Prefecture3.rb
> +class Prefecture3 < ActiveHash::Base
こちらも。

2019-07-02 05:18 UTC, RyoheiKoga commented
# what
itemsコントローラーにbefore_actionの定義
activehash命名変更

# why
可読性、命名規則にそった修正

# メンターさん
いつもお疲れ様です。
よろしくお願いします。

2019-07-02 05:22 UTC, TOMARUMARU commented on app/controllers/items_controller.rb
> +  before_action :set_item
actionを指定しましょう

2019-07-02 05:22 UTC, TOMARUMARU commented on app/controllers/items_controller.rb
> +    set_item
こちらは消しましょう

2019-07-02 05:22 UTC, TOMARUMARU commented on app/controllers/items_controller.rb
> +    set_item
こちらも

2019-07-02 05:22 UTC, TOMARUMARU commented on app/controllers/items_controller.rb
> +    set_item
こちらも

2019-07-02 06:09 UTC, RyoheiKoga commented
# what
before_actionのexcept化

# why
シンプルなコーディングのため

# メンターさん
いつもお疲れ様です。
よろしくお願いします。

2019-07-02 06:12 UTC, shingoteshima commented on app/controllers/items_controller.rb
>      item = Item.find(params[:id])
こちらもset_item使えますね。
before_actionにupdate追加してこちらの記述を消して、updateアクションの中のitemを@itemと変更しましょう。

2019-07-02 06:33 UTC, RyoheiKoga commented
# what
before_actionのaction指定

# why
シンプルなコーディングのため

# メンターさん
いつもお疲れ様です。
よろしくお願いします。

2019-07-02 06:36 UTC, TOMARUMARU approved these changes
LGTM

2019-07-02 06:48 UTC, merged